### ISSUE TITLE
HTML - Vista selección categoría de publicaciones

### ISSUE THREAD

**Issue by UzielLopez** [UzielLopez/Colpos-foros#1]
Crear el HTML para la página dónde el usuario va a poder seleccionar la categoría de publicaciones que quiere ver. 
**Esta es la página principal.**

Debe contener un dropdown menu para seleccionar la categoría y un espacio donde desplegar las publicaciones.

**Comment by Daniel-dadu** [comment]
Mockup de este issue:
![MockupHTMLIndex](https://user-images.githubusercontent.com/67434516/116501661-ff6ef080-a876-11eb-9826-fd934d68a57d.png)
