### ISSUE TITLE
HTML - Vista dentro de una publicación

### ISSUE THREAD

**Issue by UzielLopez** [UzielLopez/Colpos-foros#2]
HTML que despliegue todas las respuestas a una publicación y a su vez tenga un espacio para realizar una nueva respuesta.

**Comment by Daniel-dadu** [comment]
Mockup de issue:
![MockupHTMLIndex](https://user-images.githubusercontent.com/67434516/116501451-69d36100-a876-11eb-9e87-87844cc27d97.png)

**Comment by Daniel-dadu** [comment]
Mockup de este issue:
![MockupHTMLpublicacion](https://user-images.githubusercontent.com/67434516/116501624-e5cda900-a876-11eb-9c2b-83ebcc68d7f0.png)
