### ISSUE TITLE
CSS - Vista selección categoría de publicaciones

### ISSUE THREAD

**Issue by Fer-Rodriguez** [UzielLopez/Colpos-foros#6]
CSS correspondiente para la página principal, donde serán mostradas las publicaciones, así como el poder postear una publicación nueva.

**Comment by Daniel-dadu** [comment]
Mockup de este issue:
![MockupCSSIndex](https://user-images.githubusercontent.com/67434516/116509031-2eda2900-a888-11eb-8448-22eeb5ee83c0.png)
