### ISSUE TITLE
JavaScript - Vista selección categoría de publicaciones

### ISSUE THREAD

**Issue by UzielLopez** [UzielLopez/Colpos-foros#7]
Se debe de programar el javascript para:
-  Hacer la página interactiva
-  Permitir rescatar la información relevante de la API

**Comment by Daniel-dadu** [comment]
Mockup de este issue:
![MockupJSIndex](https://user-images.githubusercontent.com/67434516/116518284-aa8ea280-a895-11eb-89a4-2c97d61a1d98.png)
